### ISSUE TITLE
Is there a back-end registration sample Using Installation model?

### ISSUE THREAD

**Issue by giladwe** [saramgsilva/NotificationHubs#3]
i didn't find a reference for the code in https://msdn.microsoft.com/en-us/magazine/dn948105.aspx
for exmaple:
await _notificationHubClient.CreateOrUpdateInstallationAsync(installation);

**Comment by saramgsilva** [comment]
Hello, at this moment I do no have any sample using Installation model and that method is available if  you use this nuget:
https://www.nuget.org/packages/Microsoft.Azure.NotificationHubs/
