### ISSUE TITLE
Case 2 - Xamarin Android gcm client help

### ISSUE THREAD

**Issue by chitankensuru** [saramgsilva/NotificationHubs#4]
Been trying to implement parts of your case 2 project. But I get stuck at the GcmClient.Register. For some reason it never calls the OnRegistered function. I set the required package name in the broadcast receiver and I pass along a valid SenderID. Still no luck. If you have some time to help me some I'd really appreciate it.

**Comment by saramgsilva** [comment]
Hello,

at this moment I do not know what can be, but I could say maybe you missed something, in the steps provides. Did provide the correct google Id, and ...!?

**Comment by chitankensuru** [comment]
Read up a bit about it and it seems that the way you get a PNS in your example for Android has been depreciated. I followed this [Tutorial](https://developer.xamarin.com/guides/cross-platform/application_fundamentals/notifications/android/remote_notifications_in_android/) and got a PNS now. :+1:
